---
title: The structure of ForestGEO's software
author: Mauro Lepore
date: '2018-02-05'
slug: the-structure-of-forestgeo-s-software
categories: []
tags:
  - fgeo
  - R
  - devtools
  - github
  - install
---

The goal of this post is to introduce you to the fundamental structure of ForestGEO's software.

The one place to find information about ForestGEO software is the website of the [__fgeo__ package](https://forestgeo.github.io/fgeo/). __fgeo__ is a kind of umbrella: It is a meta-package that gathers multiple modules of ForestGEO's software -- each module corresponding to an individual package. Right now __fgeo__ contains a number of packages, including [__fgeo.map__](https://forestgeo.github.io/fgeo.map/), [__fgeo.tool__](https://forestgeo.github.io/fgeo.tool/) and [__fgeo.habitat__](https://forestgeo.github.io/fgeo.habitat/). This modularity facilitates managing and expanding ForestGEO's software, by adding features to preexisting or new modules (packages).

From  fgeo's website you can find [links to the individual packages](https://forestgeo.github.io/fgeo/reference/index.html), and then to the functions in each package. For example, this sequence of clicks takes you from the home page of __fgeo__ to the help file of the functin `maply_quad`: [fgeo](https://forestgeo.github.io/fgeo/index.html) > [Packages](https://forestgeo.github.io/fgeo/reference/index.html) > [fgeo.map](https://forestgeo.github.io/fgeo/reference/fgeo.map.html) > [Learn more about fgeo.map](https://forestgeo.github.io/fgeo.map/) > [Functions Index](https://forestgeo.github.io/fgeo.map/reference/index.html) > [maply_quad](https://forestgeo.github.io/fgeo.map/reference/maply_quad.html). You may also want to visit the [Tutorials](https://forestgeo.github.io/fgeo.map/articles/index.html) tab and the [Apps](https://bookdown.org/forestgeoguest/map_tag_app/) tab.

The easiest way to get all of ForestGEO's software is by [installing fgeo](https://forestgeo.github.io/fgeo/index.html#installation) and then loading all packages in one call with `library(fgeo)`. Installing __fgeo__ takes longer than, say, only  [installing __fgeo.map__](https://forestgeo.github.io/fgeo.map/#installation). But you have to go over this pain only once (and every time you want to update all packages). The links in this paragraph give installation instructions that might be too succinct. For more details on how to install packages from GitHub you may want to read [this short blog post](https://fgeo.netlify.com/2018/02/05/2018-02-05-installing-packages-from-github/).

