---
title: Installing packages from GitHub
author: Mauro Lepore
date: '2018-02-05'
slug: installing-packages-from-github
categories: []
tags:
  - R
  - r rstudio
  - remotes
  - fgeo
  - devtools
  - install
  - github
  - packages
---

R packages live most commonly on [CRAN](https://cran.r-project.org/) or [GitHub](https://github.com/). To install packages that live on CRAN you use the function `install.packages()` which comes by default with R. 
To install packages that live on GitHub you use the function `install_github()`, which comes not by default but with the packages __devtools__ and __remotes__. I recommend __remotes__ because it is lighter. __remotes__ lives in CRAN, so you can install it with:

```
install.packages("remotes")
```

R packages are like any other software. To use an R package -- or any software -- you need to install it once, and then "open" (load) it every time you want to use it. In R you load a package with `library(package)`. Let's open __remotes__: 

```
library(remotes)
```

Now you can use the function `install_github()`. The description and examples of the help file `?install_github()` show you what to do next. You need to feed `install_github()` with a username and a repository name. For example, this is what you should run if you want to install the package __tidyverse__ from the GitHub username "hadley":

```
install_github("hadley/tidyverse")
```

There is a way to save a little typing. You can use `install_github()` without running `library(remotes)`: This is how:

```
remotes::install_github("hadley/tidyverse")
```

The syntax `package::function` works for any package. For example, had you installed __devtools__, you could also install __tidyverse__ with:

```
devtools::install_github("hadley/tidyverse")
```

And now you can "open" __tidyverse__ and start using it. For example:

```
# Open
library(tidyverse)
# Use
tidyverse_update()
```

Or you can use the syntax you just learned:

```
tidyverse::tidyverse_update()
```

To learn what a package does you can run `help(package = "package-you-want-to-know-about")`. For example:

```
help(package = "tidyverse")
```

# Further reading

[Other blogs about packages](https://fgeo.netlify.com/tags/packages/)
