---
title: Mapping elevation
author: Mauro Lepore
date: '2018-05-16'
slug: mapping-elevation
categories: []
tags:
  - fgeo
  - map
  - elevation
  - tutorial
  - example
  - Mpala
  - Africa
description: ''
---


```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# hadley's settings
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,  # {mine}
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  out.width = "100%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  rows.print = 3  # {mine}
)
```

# Easiest

```{r, echo=FALSE}
load(here::here("../try/inst/private/CTFSElev_mpala.rdata"))
```

```{r}
# https://forestgeo.github.io/fgeo.map/
library(fgeo.map)

# Load your own elevation data
elevation <- CTFSElev_mpala

# You can use the elevation data in the elevation list directly
str(elevation)
map_elev(elevation)
```

```{r}
# Also, you can extract the elevation dataframe and use that
elev <- elevation$col
map_elev(elev)
```

```{r}
# You have a number of options you can tweak
map_elev(elev,
  # Or choose colors by code from http://bit.ly/2rJgQba
  low = "grey", high = "black", 
  # How many lines, and how thick
  bins = 100, contour_size = 0.5,
  # Hide elevation numbers from inside the plot
  label_elev = FALSE, 
  # Keep the "level" legend
  hide_legend_color = FALSE
)
```


# More flexible

```{r}
# http://ggplot2.tidyverse.org/reference/
library(ggplot2)

ggplot(elev, aes(x = x, y = y, z = elev)) +
  geom_raster(aes(fill = elev)) +
  geom_contour(color = "white", bins = 100) +
  scale_fill_gradient(low = "grey", high = "black") +
  coord_equal() +
  theme_bw()
```

